name: Check AWS Access

on: 
  push:
      branches:
        - main

# permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
  
jobs:
  check-access:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.1
    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          role-to-assume: arn:aws:iam::294393683200:role/github-actions-aws-demo
          role-session-name: aws-github-actions
          aws-region: ap-south-1

      - name: Verify AWS credentials
        run: aws sts get-caller-identity

